#!/bin/sh

# script/publish: Build and upload to github pages

set -e

cd "$(dirname "$0")/.."

echo "Compiling..."
elm make src/Main.elm --optimize --output build/main.js > /dev/null

echo "Compressing..."
curl \
  --silent \
  --data-urlencode "js_code@build/main.js" \
  --data output_info=compiled_code \
  --data output_format=text \
  --data compilation_level=ADVANCED_OPTIMIZATIONS \
  --output build/main.min.js \
  https://closure-compiler.appspot.com/compile

TEMPORARY_DIRECTORY=`mktemp -d`
cp -r build/. $TEMPORARY_DIRECTORY
cd $TEMPORARY_DIRECTORY

git init
git add .
git commit -m "Build commit"
git remote add origin git@github.com:sch/l-system.git
git push origin HEAD:gh-pages --force
